source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gemspec

group :jekyll_plugins do
  gem "jekyll-last-modified-at"
  gem "html-proofer", "~> 3.19.3"
  gem 'jekyll-seo-tag'
  gem "jekyll-sitemap", "~> 1.4.0"
  gem "jemoji", "~> 0.12.0"
  gem "rake", "~> 13.0.6"
end
